excluded: # paths to ignore during linting. Takes precedence over `included`.
  - MercadoPagoSDKTests
  - Pods
force_cast: warning # implicitly
force_unwrapping: error


file_length:
  warning: 900
  error: 1200
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
variable_name:
  max_length:
    warning: 55
    error: 60
  excluded:
    - url
type_body_length:
   warning: 300
   error: 900
function_body_length:
   warning: 50
   error: 100
cyclomatic_complexity:
   warning: 10
   error: 15

function_parameter_count:
  warning: 8
  error: 10

opt_in_rules:

  - closure_spacing
  - redundant_nil_coalescing
  - nimble_operator
  - operator_usage_whitespace
  - closure_end_indentation
  - object_literal
  - prohibited_super_call
  - empty_parameters
  - conditional_returns_on_newline

  # - empty_count
  # - private_outlet
  # - explicit_init
  # - overridden_super_call


disabled_rules:
  - large_tuple
  - line_length
  - cyclomatic_complexity
  - operator_whitespace
  - todo
  - force_cast
  - implicit_getter
  - legacy_constructor
  - variable_name



# disabled_rules:
#     - trailing_newline
#     - opening_brace
#     - empty_count
#     - comma
#     - colon
#     - force_cast
#     - type_name
#     - variable_name_min_length
#     - trailing_semicolon
#     - force_try
#     - function_body_length
#     - nesting
#     - variable_name
#     - conditional_binding_cascade
#     - variable_name_max_length
#     - operator_whitespace
#     - control_statement
#     - legacy_constant
#     - line_length
#     - return_arrow_whitespace
#     - trailing_whitespace
#     - closing_brace
#     - statement_position
#     - type_body_length
#     - todo
#     - legacy_constructor
#     - valid_docs
#     - missing_docs
#     - file_length
#     - leading_whitespace
